In [4]:
from pyfaidx import Fasta
import pyranges as pr

In [ ]:
Lzep_ref = Fasta("./Jones_NEE_2023_Lzep/ref/Lasioglossum_zephyrus.fasta")
names = list(Lzep_ref.keys())
names

['LZEP_unplaced_11829',
 'LZEP_unplaced_7288',
 'LZEP_unplaced_11828',
 'LZEP_unplaced_8237',
 'LZEP_unplaced_10352',
 'LZEP_unplaced_8236',
 'LZEP_unplaced_8235',
 'LZEP_unplaced_8234',
 'LZEP_unplaced_10163',
 'LZEP_unplaced_8584',
 'LZEP_unplaced_10353',
 'LZEP_unplaced_9645',
 'LZEP_unplaced_11823',
 'LZEP_unplaced_11822',
 'LZEP_unplaced_10354',
 'LZEP_unplaced_9644',
 'LZEP_unplaced_11801',
 'LZEP_unplaced_14363',
 'LZEP_unplaced_9560',
 'LZEP_unplaced_10355',
 'LZEP_unplaced_12980',
 'LZEP_unplaced_9647',
 'LZEP_unplaced_9230',
 'LZEP_unplaced_9231',
 'LZEP_unplaced_9232',
 'LZEP_unplaced_9233',
 'LZEP_unplaced_9234',
 'LZEP_unplaced_9235',
 'LZEP_unplaced_9236',
 'LZEP_unplaced_9237',
 'LZEP_unplaced_9238',
 'LZEP_unplaced_9239',
 'LZEP_unplaced_10356',
 'LZEP_unplaced_9646',
 'LZEP_unplaced_11778',
 'LZEP_unplaced_9151',
 'LZEP_unplaced_5551',
 'LZEP_unplaced_5550',
 'LZEP_unplaced_5553',
 'LZEP_unplaced_5552',
 'LZEP_unplaced_5555',
 'LZEP_unplaced_5554',
 'LZEP_unplaced_5557',
 'LZEP_unplaced_5556',
 'LZEP_unplaced_5559',
 'LZEP_unplaced_5558',
 'LZEP_unplaced_10600',
 'LZEP_unplaced_10601',
 'LZEP_unplaced_10606',
 'LZEP_unplaced_10607',
 'LZEP_unplaced_10604',
 'LZEP_unplaced_10605',
 'LZEP_unplaced_10357',
 'LZEP_unplaced_4978',
 'LZEP_unplaced_4979',
 'LZEP_unplaced_4974',
 'LZEP_unplaced_4975',
 'LZEP_unplaced_4976',
 'LZEP_unplaced_4977',
 'LZEP_unplaced_4970',
 'LZEP_unplaced_4971',
 'LZEP_unplaced_4972',
 'LZEP_unplaced_4973',
 'LZEP_unplaced_9640',
 'LZEP_unplaced_8123',
 'LZEP_unplaced_8122',
 'LZEP_unplaced_8121',
 'LZEP_unplaced_8120',
 'LZEP_unplaced_8127',
 'LZEP_unplaced_8126',
 'LZEP_unplaced_8125',
 'LZEP_unplaced_8124',
 'LZEP_unplaced_8129',
 'LZEP_unplaced_8128',
 'LZEP_unplaced_9643',
 'LZEP_unplaced_9152',
 'LZEP_unplaced_11975',
 'LZEP_unplaced_9192',
 'LZEP_unplaced_9642',
 'LZEP_unplaced_9155',
 'LZEP_unplaced_2329',
 'LZEP_unplaced_2328',
 'LZEP_unplaced_2327',
 'LZEP_unplaced_2326',
 'LZEP_unplaced_2325',
 'LZEP_unplaced_2324',
 'LZEP_unplaced_2323',
 'LZEP_unplaced_2322',
 'LZEP_unplaced_2321',
 'LZEP_unplaced_2320',
 'LZEP_unplaced_4208',
 'LZEP_unplaced_4209',
 'LZEP_unplaced_4206',
 'LZEP_unplaced_4207',
 'LZEP_unplaced_4204',
 'LZEP_unplaced_4205',
 'LZEP_unplaced_4202',
 'LZEP_unplaced_4203',
 'LZEP_unplaced_4200',
 'LZEP_unplaced_4201',
 'LZEP_unplaced_11559',
 'LZEP_unplaced_11558',
 'LZEP_unplaced_11053',
 'LZEP_unplaced_11551',
 'LZEP_unplaced_11550',
 'LZEP_unplaced_11553',
 'LZEP_unplaced_11552',
 'LZEP_unplaced_11555',
 'LZEP_unplaced_11554',
 'LZEP_unplaced_11557',
 'LZEP_unplaced_11055',
 'LZEP_unplaced_13657',
 'LZEP_unplaced_8787',
 'LZEP_unplaced_8786',
 'LZEP_unplaced_8785',
 'LZEP_unplaced_8784',
 'LZEP_unplaced_8783',
 'LZEP_unplaced_8782',
 'LZEP_unplaced_8781',
 'LZEP_unplaced_8780',
 'LZEP_unplaced_8789',
 'LZEP_unplaced_8788',
 'LZEP_unplaced_12921',
 'LZEP_unplaced_12920',
 'LZEP_unplaced_12923',
 'LZEP_unplaced_12922',
 'LZEP_unplaced_12925',
 'LZEP_unplaced_12924',
 'LZEP_unplaced_12927',
 'LZEP_unplaced_12926',
 'LZEP_unplaced_12929',
 'LZEP_unplaced_12928',
 'LZEP_unplaced_7153',
 'LZEP_unplaced_7152',
 'LZEP_unplaced_7151',
 'LZEP_unplaced_7150',
 'LZEP_unplaced_7157',
 'LZEP_unplaced_7156',
 'LZEP_unplaced_7155',
 'LZEP_unplaced_7154',
 'LZEP_unplaced_7159',
 'LZEP_unplaced_7158',
 'LZEP_unplaced_13667',
 'LZEP_unplaced_13666',
 'LZEP_unplaced_13661',
 'LZEP_unplaced_13660',
 'LZEP_unplaced_8871',
 'LZEP_unplaced_8870',
 'LZEP_unplaced_8873',
 'LZEP_unplaced_8872',
 'LZEP_unplaced_8875',
 'LZEP_unplaced_8874',
 'LZEP_unplaced_8877',
 'LZEP_unplaced_8876',
 'LZEP_unplaced_8879',
 'LZEP_unplaced_7064',
 'LZEP_unplaced_11168',
 'LZEP_unplaced_3445',
 'LZEP_unplaced_12981',
 'LZEP_unplaced_3444',
 'LZEP_unplaced_11160',
 'LZEP_unplaced_11161',
 'LZEP_unplaced_11162',
 'LZEP_unplaced_11163',
 'LZEP_unplaced_9990',
 'LZEP_unplaced_3111',
 'LZEP_unplaced_11166',
 'LZEP_unplaced_11167',
 'LZEP_unplaced_9724',
 'LZEP_unplaced_3110',
 'LZEP_unplaced_3441',
 'LZEP_unplaced_13639',
 'LZEP_unplaced_3116',
 'LZEP_unplaced_3115',
 'LZEP_unplaced_3114',
 'LZEP_unplaced_9725',
 'LZEP_unplaced_9722',
 'LZEP_unplaced_13637',
 'LZEP_unplaced_6200',
 'LZEP_unplaced_6201',
 'LZEP_unplaced_6202',
 'LZEP_unplaced_6203',
 'LZEP_unplaced_6204',
 'LZEP_unplaced_6205',
 'LZEP_unplaced_6206',
 'LZEP_unplaced_6207',
 'LZEP_unplaced_6208',
 'LZEP_unplaced_6209',
 'LZEP_unplaced_10385',
 'LZEP_unplaced_9723',
 'LZEP_unplaced_10383',
 'LZEP_unplaced_10382',
 'LZEP_unplaced_10381',
 'LZEP_unplaced_10380',
 'LZEP_unplaced_12795',
 'LZEP_unplaced_14303',
 'LZEP_unplaced_9720',
 'LZEP_unplaced_9721',
 'LZEP_unplaced_11836',
 'LZEP_unplaced_5871',
 'LZEP_unplaced_11834',
 'LZEP_unplaced_11835',
 'LZEP_unplaced_11832',
 'LZEP_unplaced_11833',
 'LZEP_unplaced_11830',
 'LZEP_unplaced_11831',
 'LZEP_unplaced_11838',
 'LZEP_unplaced_11839',
 'LZEP_unplaced_278',
 'LZEP_unplaced_279',
 'LZEP_unplaced_13633',
 'LZEP_unplaced_270',
 'LZEP_unplaced_271',
 'LZEP_unplaced_272',
 'LZEP_unplaced_273',
 'LZEP_unplaced_274',
 'LZEP_unplaced_275',
 'LZEP_unplaced_276',
 'LZEP_unplaced_277',
 'LZEP_unplaced_5038',
 'LZEP_unplaced_5039',
 'LZEP_unplaced_1009',
 'LZEP_unplaced_1008',
 'LZEP_unplaced_1007',
 'LZEP_unplaced_1006',
 'LZEP_unplaced_1005',
 'LZEP_unplaced_1004',
 'LZEP_unplaced_1003',
 'LZEP_unplaced_1002',
 'LZEP_unplaced_1001',
 'LZEP_unplaced_1000',
 'LZEP_unplaced_4789',
 'LZEP_unplaced_4788',
 'LZEP_unplaced_4783',
 'LZEP_unplaced_4782',
 'LZEP_unplaced_4781',
 'LZEP_unplaced_4780',
 'LZEP_unplaced_4787',
 'LZEP_unplaced_4786',
 'LZEP_unplaced_4785',
 'LZEP_unplaced_4784',
 'LZEP_unplaced_10133',
 'LZEP_unplaced_14302',
 'LZEP_unplaced_13631',
 'LZEP_unplaced_13096',
 'LZEP_unplaced_13097',
 'LZEP_unplaced_13094',
 'LZEP_unplaced_13095',
 'LZEP_unplaced_13092',
 'LZEP_unplaced_13093',
 'LZEP_unplaced_13090',
 'LZEP_unplaced_13091',
 'LZEP_unplaced_13098',
 'LZEP_unplaced_13099',
 'LZEP_unplaced_5784',
 'LZEP_unplaced_5785',
 'LZEP_unplaced_1269',
 'LZEP_unplaced_1268',
 'LZEP_unplaced_5780',
 'LZEP_unplaced_5781',
 'LZEP_unplaced_5782',
 'LZEP_unplaced_5783',
 'LZEP_unplaced_1263',
 'LZEP_unplaced_1262',
 'LZEP_unplaced_1261',
 'LZEP_unplaced_1260',
 'LZEP_unplaced_1267',
 'LZEP_unplaced_1266',
 'LZEP_unplaced_1265',
 'LZEP_unplaced_1264',
 'LZEP_unplaced_4567',
 'LZEP_unplaced_4566',
 'LZEP_unplaced_4565',
 'LZEP_unplaced_4564',
 'LZEP_unplaced_4563',
 'LZEP_unplaced_4562',
 'LZEP_unplaced_4561',
 'LZEP_unplaced_4560',
 'LZEP_unplaced_11766',
 'LZEP_unplaced_11767',
 'LZEP_unplaced_11764',
 'LZEP_unplaced_11765',
 'LZEP_unplaced_11762',
 'LZEP_unplaced_11763',
 'LZEP_unplaced_4569',
 'LZEP_unplaced_4568',
 'LZEP_unplaced_5223',
 'LZEP_unplaced_5222',
 'LZEP_unplaced_13559',
 'LZEP_unplaced_5221',
 'LZEP_unplaced_13540',
 'LZEP_unplaced_13541',
 'LZEP_unplaced_13542',
 'LZEP_unplaced_5220',
 'LZEP_unplaced_13544',
 'LZEP_unplaced_13545',
 'LZEP_unplaced_13546',
 'LZEP_unplaced_13547',
 'LZEP_unplaced_13548',
 'LZEP_unplaced_5227',
 'LZEP_unplaced_10819',
 'LZEP_unplaced_5226',
 'LZEP_unplaced_12150',
 'LZEP_unplaced_12151',
 'LZEP_unplaced_12152',
 'LZEP_unplaced_12153',
 'LZEP_unplaced_12154',
 'LZEP_unplaced_5225',
 'LZEP_unplaced_12156',
 'LZEP_unplaced_12157',
 'LZEP_unplaced_12158',
 'LZEP_unplaced_12159',
 'LZEP_unplaced_5224',
 'LZEP_unplaced_11498',
 'LZEP_unplaced_9018',
 'LZEP_unplaced_9019',
 'LZEP_unplaced_11490',
 'LZEP_unplaced_11491',
 'LZEP_unplaced_11492',
 'LZEP_unplaced_11493',
 'LZEP_unplaced_11494',
 'LZEP_unplaced_11495',
 'LZEP_unplaced_11496',
 'LZEP_unplaced_11497',
 'LZEP_unplaced_13405',
 'LZEP_unplaced_13404',
 'LZEP_unplaced_13407',
 'LZEP_unplaced_13406',
 'LZEP_unplaced_13401',
 'LZEP_unplaced_13400',
 'LZEP_unplaced_13403',
 'LZEP_unplaced_13402',
 'LZEP_unplaced_13079',
 'LZEP_unplaced_13409',
 'LZEP_unplaced_13408',
 'LZEP_unplaced_1919',
 'LZEP_unplaced_1918',
 'LZEP_unplaced_1915',
 'LZEP_unplaced_1914',
 'LZEP_unplaced_1917',
 'LZEP_unplaced_1916',
 'LZEP_unplaced_1911',
 'LZEP_unplaced_1910',
 'LZEP_unplaced_1913',
 'LZEP_unplaced_1912',
 'LZEP_unplaced_14301',
 'LZEP_unplaced_9010',
 'LZEP_unplaced_11185',
 'LZEP_unplaced_9011',
 'LZEP_unplaced_9012',
 'LZEP_unplaced_9565',
 'LZEP_unplaced_11326',
 'LZEP_unplaced_9013',
 'LZEP_unplaced_11327',
 'LZEP_unplaced_9014',
 'LZEP_unplaced_8778',
 'LZEP_unplaced_9015',
 'LZEP_unplaced_3517',
 'LZEP_unplaced_3516',
 'LZEP_unplaced_3515',
 'LZEP_unplaced_3514',
 'LZEP_unplaced_3513',
 'LZEP_unplaced_3512',
 'LZEP_unplaced_3511',
 'LZEP_unplaced_3510',
 'LZEP_unplaced_11322',
 'LZEP_unplaced_9017',
 'LZEP_unplaced_3519',
 'LZEP_unplaced_3518',
 'LZEP_unplaced_5946',
 'LZEP_unplaced_11320',
 'LZEP_unplaced_10019',
 'LZEP_unplaced_10018',
 'LZEP_unplaced_10017',
 'LZEP_unplaced_10016',
 'LZEP_unplaced_10015',
 'LZEP_unplaced_10014',
 'LZEP_unplaced_10013',
 'LZEP_unplaced_10012',
 'LZEP_unplaced_10011',
 'LZEP_unplaced_10010',
 'LZEP_unplaced_10609',
 'LZEP_unplaced_11188',
 'LZEP_unplaced_10902',
 'LZEP_unplaced_8776',
 'LZEP_unplaced_8777',
 'LZEP_unplaced_10602',
 'LZEP_unplaced_7982',
 'LZEP_unplaced_13932',
 'LZEP_unplaced_10603',
 'LZEP_unplaced_472',
 'LZEP_unplaced_473',
 'LZEP_unplaced_470',
 'LZEP_unplaced_471',
 'LZEP_unplaced_476',
 'LZEP_unplaced_477',
 'LZEP_unplaced_474',
 'LZEP_unplaced_475',
 'LZEP_unplaced_478',
 'LZEP_unplaced_479',
 'LZEP_unplaced_8668',
 'LZEP_unplaced_8669',
 'LZEP_unplaced_13166',
 'LZEP_unplaced_9571',
 'LZEP_unplaced_13167',
 'LZEP_unplaced_13164',
 'LZEP_unplaced_13165',
 'LZEP_unplaced_14300',
 'LZEP_unplaced_13162',
 'LZEP_unplaced_13163',
 'LZEP_unplaced_717',
 'LZEP_unplaced_716',
 'LZEP_unplaced_715',
 'LZEP_unplaced_714',
 'LZEP_unplaced_713',
 'LZEP_unplaced_712',
 'LZEP_unplaced_711',
 'LZEP_unplaced_710',
 'LZEP_unplaced_13161',
 'LZEP_unplaced_719',
 'LZEP_unplaced_718',
 'LZEP_unplaced_2172',
 'LZEP_unplaced_2173',
 'LZEP_unplaced_2170',
 'LZEP_unplaced_2171',
 'LZEP_unplaced_2176',
 'LZEP_unplaced_2177',
 'LZEP_unplaced_2174',
 'LZEP_unplaced_2175',
 'LZEP_unplaced_2178',
 'LZEP_unplaced_2179',
 'LZEP_unplaced_7528',
 'LZEP_unplaced_7529',
 'LZEP_unplaced_7522',
 'LZEP_unplaced_7523',
 'LZEP_unplaced_7520',
 'LZEP_unplaced_7521',
 'LZEP_unplaced_7526',
 'LZEP_unplaced_7527',
 'LZEP_unplaced_7524',
 'LZEP_unplaced_7525',
 'LZEP_unplaced_6929',
 'LZEP_unplaced_6928',
 'LZEP_unplaced_6699',
 'LZEP_unplaced_6698',
 'LZEP_unplaced_6693',
 'LZEP_unplaced_6692',
 'LZEP_unplaced_6691',
 'LZEP_unplaced_6690',
 'LZEP_unplaced_6697',
 'LZEP_unplaced_6696',
 'LZEP_unplaced_6695',
 'LZEP_unplaced_6694',
 'LZEP_unplaced_12574',
 'LZEP_unplaced_12716',
 'LZEP_unplaced_12717',
 'LZEP_unplaced_12714',
 'LZEP_unplaced_12715',
 'LZEP_unplaced_12712',
 'LZEP_unplaced_12713',
 'LZEP_unplaced_12710',
 'LZEP_unplaced_12711',
 'LZEP_unplaced_9985',
 'LZEP_unplaced_9072',
 'LZEP_unplaced_12719',
 'LZEP_unplaced_14383',
 'LZEP_unplaced_9197',
 'LZEP_unplaced_14381',
 'LZEP_unplaced_12140',
 'LZEP_unplaced_12797',
 'LZEP_unplaced_12794',
 'LZEP_unplaced_6077',
 'LZEP_unplaced_6076',
 'LZEP_unplaced_6075',
 'LZEP_unplaced_6074',
 'LZEP_unplaced_6073',
 'LZEP_unplaced_6072',
 'LZEP_unplaced_6071',
 'LZEP_unplaced_6070',
 'LZEP_unplaced_12144',
 'LZEP_unplaced_6079',
 'LZEP_unplaced_6078',
 'LZEP_unplaced_12439',
 'LZEP_unplaced_12438',
 'LZEP_unplaced_12433',
 'LZEP_unplaced_12432',
 'LZEP_unplaced_12431',
 'LZEP_unplaced_12430',
 'LZEP_unplaced_12437',
 'LZEP_unplaced_12436',
 'LZEP_unplaced_12435',
 'LZEP_unplaced_12434',
 'LZEP_unplaced_9070',
 'LZEP_unplaced_14309',
 'LZEP_unplaced_942',
 'LZEP_unplaced_14308',
 'LZEP_unplaced_13395',
 'LZEP_unplaced_13394',
 'LZEP_unplaced_13397',
 'LZEP_unplaced_13396',
 'LZEP_unplaced_13391',
 'LZEP_unplaced_9980',
 'LZEP_unplaced_13393',
 'LZEP_unplaced_13392',
 'LZEP_unplaced_7634',
 'LZEP_unplaced_13399',
 'LZEP_unplaced_13398',
 'LZEP_unplaced_12385',
 'LZEP_unplaced_6760',
 'LZEP_unplaced_12387',
 'LZEP_unplaced_12386',
 'LZEP_unplaced_12381',
 'LZEP_unplaced_12380',
 'LZEP_unplaced_12383',
 'LZEP_unplaced_12382',
 'LZEP_unplaced_12389',
 'LZEP_unplaced_12388',
 'LZEP_unplaced_9981',
 'LZEP_unplaced_9193',
 'LZEP_unplaced_14306',
 'LZEP_unplaced_14305',
 'LZEP_unplaced_14304',
 'LZEP_unplaced_8596',
 'LZEP_unplaced_12930',
 'LZEP_unplaced_8597',
 'LZEP_unplaced_10316',
 'LZEP_unplaced_11486',
 'LZEP_unplaced_10837',
 'LZEP_unplaced_8595',
 'LZEP_unplaced_10310',
 'LZEP_unplaced_11484',
 'LZEP_unplaced_13982',
 'LZEP_unplaced_10311',
 'LZEP_unplaced_9258',
 'LZEP_unplaced_9259',
 'LZEP_unplaced_10312',
 'LZEP_unplaced_9825',
 'LZEP_unplaced_13439',
 'LZEP_unplaced_9252',
 'LZEP_unplaced_9253',
 'LZEP_unplaced_9250',
 'LZEP_unplaced_9251',
 'LZEP_unplaced_9256',
 'LZEP_unplaced_9257',
 'LZEP_unplaced_9254',
 'LZEP_unplaced_9255',
 'LZEP_unplaced_2241',
 'LZEP_unplaced_10868',
 'LZEP_unplaced_9568',
 'LZEP_unplaced_5579',
 'LZEP_unplaced_5578',
 'LZEP_unplaced_5573',
 'LZEP_unplaced_5572',
 'LZEP_unplaced_5571',
 'LZEP_unplaced_5570',
 'LZEP_unplaced_5577',
 'LZEP_unplaced_5576',
 'LZEP_unplaced_5575',
 'LZEP_unplaced_5574',
 'LZEP_unplaced_8598',
 'LZEP_unplaced_13431',
 'LZEP_unplaced_2247',
 'LZEP_unplaced_4996',
 'LZEP_unplaced_4997',
 'LZEP_unplaced_4994',
 'LZEP_unplaced_4995',
 'LZEP_unplaced_4992',
 'LZEP_unplaced_4993',
 'LZEP_unplaced_4990',
 'LZEP_unplaced_4991',
 'LZEP_unplaced_4998',
 'LZEP_unplaced_4999',
 'LZEP_unplaced_13437',
 'LZEP_unplaced_12374',
 'LZEP_unplaced_4198',
 'LZEP_unplaced_4199',
 'LZEP_unplaced_4196',
 'LZEP_unplaced_4197',
 'LZEP_unplaced_4194',
 'LZEP_unplaced_4195',
 'LZEP_unplaced_4192',
 'LZEP_unplaced_4193',
 'LZEP_unplaced_4190',
 'LZEP_unplaced_4191',
 'LZEP_unplaced_11808',
 'LZEP_unplaced_13983',
 'LZEP_unplaced_2349',
 'LZEP_unplaced_2348',
 'LZEP_unplaced_2341',
 'LZEP_unplaced_2340',
 'LZEP_unplaced_2343',
 'LZEP_unplaced_2342',
 'LZEP_unplaced_2345',
 'LZEP_unplaced_2344',
 'LZEP_unplaced_2347',
 'LZEP_unplaced_2346',
 'LZEP_unplaced_4228',
 'LZEP_unplaced_4229',
 'LZEP_unplaced_9569',
 'LZEP_unplaced_4220',
 'LZEP_unplaced_4221',
 'LZEP_unplaced_4222',
 'LZEP_unplaced_4223',
 'LZEP_unplaced_4224',
 'LZEP_unplaced_4225',
 'LZEP_unplaced_4226',
 'LZEP_unplaced_4227',
 'LZEP_unplaced_11533',
 'LZEP_unplaced_11532',
 'LZEP_unplaced_11531',
 'LZEP_unplaced_11530',
 'LZEP_unplaced_11537',
 'LZEP_unplaced_11536',
 'LZEP_unplaced_11535',
 'LZEP_unplaced_11534',
 'LZEP_unplaced_11539',
 'LZEP_unplaced_11538',
 'LZEP_unplaced_12949',
 'LZEP_unplaced_12948',
 'LZEP_unplaced_12943',
 'LZEP_unplaced_12942',
 'LZEP_unplaced_12941',
 'LZEP_unplaced_12940',
 'LZEP_unplaced_12947',
 'LZEP_unplaced_12946',
 'LZEP_unplaced_12945',
 'LZEP_unplaced_12944',
 'LZEP_unplaced_9133',
 'LZEP_unplaced_13651',
 'LZEP_unplaced_3168',
 'LZEP_unplaced_3169',
 'LZEP_unplaced_3166',
 'LZEP_unplaced_3167',
 'LZEP_unplaced_3164',
 'LZEP_unplaced_3165',
 'LZEP_unplaced_3162',
 'LZEP_unplaced_3163',
 'LZEP_unplaced_3160',
 'LZEP_unplaced_3161',
 'LZEP_unplaced_8562',
 'LZEP_unplaced_9132',
 'LZEP_unplaced_11142',
 'LZEP_unplaced_8561',
 'LZEP_unplaced_11140',
 'LZEP_unplaced_11141',
 'LZEP_unplaced_11146',
 'LZEP_unplaced_11147',
 'LZEP_unplaced_11144',
 'LZEP_unplaced_11145',
 'LZEP_unplaced_8026',
 'LZEP_unplaced_9131',
 'LZEP_unplaced_11149',
 'LZEP_unplaced_9465',
 'LZEP_unplaced_58',
 'LZEP_unplaced_8560',
 'LZEP_unplaced_9130',
 'LZEP_unplaced_9460',
 'LZEP_unplaced_9462',
 'LZEP_unplaced_8567',
 'LZEP_unplaced_5102',
 'LZEP_unplaced_5103',
 'LZEP_unplaced_5410',
 'LZEP_unplaced_5100',
 'LZEP_unplaced_6268',
 'LZEP_unplaced_52',
 'LZEP_unplaced_6262',
 'LZEP_unplaced_5106',
 'LZEP_unplaced_6260',
 'LZEP_unplaced_6261',
 'LZEP_unplaced_6266',
 'LZEP_unplaced_6267',
 'LZEP_unplaced_6264',
 'LZEP_unplaced_5107',
 'LZEP_unplaced_10817',
 'LZEP_unplaced_10816',
 'LZEP_unplaced_8859',
 'LZEP_unplaced_8858',
 'LZEP_unplaced_8509',
 'LZEP_unplaced_5104',
 'LZEP_unplaced_10811',
 'LZEP_unplaced_10810',
 'LZEP_unplaced_8505',
 'LZEP_unplaced_8504',
 'LZEP_unplaced_8507',
 'LZEP_unplaced_1130',
 'LZEP_unplaced_8501',
 'LZEP_unplaced_8500',
 'LZEP_unplaced_8503',
 'LZEP_unplaced_8502',
 'LZEP_unplaced_3603',
 'LZEP_unplaced_3602',
 'LZEP_unplaced_8565',
 'LZEP_unplaced_3601',
 'LZEP_unplaced_3600',
 'LZEP_unplaced_3607',
 'LZEP_unplaced_3606',
 'LZEP_unplaced_6613',
 'LZEP_unplaced_3605',
 'LZEP_unplaced_6612',
 'LZEP_unplaced_9826',
 'LZEP_unplaced_3604',
 'LZEP_unplaced_6611',
 'LZEP_unplaced_6610',
 'LZEP_unplaced_6617',
 'LZEP_unplaced_6616',
 'LZEP_unplaced_11850',
 'LZEP_unplaced_11851',
 'LZEP_unplaced_11852',
 'LZEP_unplaced_11853',
 'LZEP_unplaced_11854',
 'LZEP_unplaced_6615',
 'LZEP_unplaced_11856',
 'LZEP_unplaced_11857',
 'LZEP_unplaced_11858',
 'LZEP_unplaced_11859',
 'LZEP_unplaced_6614',
 'LZEP_unplaced_14158',
 'LZEP_unplaced_9280',
 'LZEP_unplaced_7742',
 'LZEP_unplaced_6488',
 'LZEP_unplaced_6489',
 'LZEP_unplaced_6486',
 'LZEP_unplaced_6487',
 'LZEP_unplaced_6484',
 'LZEP_unplaced_6485',
 'LZEP_unplaced_6482',
 'LZEP_unplaced_6483',
 'LZEP_unplaced_6480',
 'LZEP_unplaced_6481',
 'LZEP_unplaced_296',
 'LZEP_unplaced_297',
 'LZEP_unplaced_294',
 'LZEP_unplaced_295',
 'LZEP_unplaced_292',
 'LZEP_unplaced_293',
 'LZEP_unplaced_290',
 'LZEP_unplaced_291',
 'LZEP_unplaced_7746',
 'LZEP_unplaced_298',
 'LZEP_unplaced_299',
 'LZEP_unplaced_1069',
 'LZEP_unplaced_1068',
 'LZEP_unplaced_5016',
 'LZEP_unplaced_5017',
 'LZEP_unplaced_5010',
 'LZEP_unplaced_5011',
 'LZEP_unplaced_5012',
 'LZEP_unplaced_5013',
 'LZEP_unplaced_1061',
 'LZEP_unplaced_1060',
 'LZEP_unplaced_1063',
 'LZEP_unplaced_1062',
 'LZEP_unplaced_1065',
 'LZEP_unplaced_1064',
 'LZEP_unplaced_1067',
 'LZEP_unplaced_1066',
 'LZEP_unplaced_4765',
 'LZEP_unplaced_4764',
 'LZEP_unplaced_4767',
 'LZEP_unplaced_4766',
 'LZEP_unplaced_4761',
 'LZEP_unplaced_4760',
 'LZEP_unplaced_4763',
 'LZEP_unplaced_4762',
 'LZEP_unplaced_14075',
 'LZEP_unplaced_9139',
 'LZEP_unplaced_4769',
 'LZEP_unplaced_4768',
 'LZEP_unplaced_14074',
 'LZEP_unplaced_1343',
 'LZEP_unplaced_14077',
 'LZEP_unplaced_10156',
 'LZEP_unplaced_1344',
 'LZEP_unplaced_11556',
 'LZEP_unplaced_1345',
 'LZEP_unplaced_5729',
 'LZEP_unplaced_1346',
 'LZEP_unplaced_9138',
 'LZEP_unplaced_1347',
 'LZEP_unplaced_1285',
 'LZEP_unplaced_1284',
 'LZEP_unplaced_1287',
 'LZEP_unplaced_1286',
 'LZEP_unplaced_1281',
 'LZEP_unplaced_1280',
 'LZEP_unplaced_1283',
 'LZEP_unplaced_1282',
 'LZEP_unplaced_5908',
 'LZEP_unplaced_5909',
 'LZEP_unplaced_1289',
 'LZEP_unplaced_1288',
 'LZEP_unplaced_4501',
 'LZEP_unplaced_4500',
 'LZEP_unplaced_4503',
 'LZEP_unplaced_4502',
 'LZEP_unplaced_4505',
 'LZEP_unplaced_4504',
 'LZEP_unplaced_4507',
 'LZEP_unplaced_4506',
 'LZEP_unplaced_4509',
 'LZEP_unplaced_4508',
 'LZEP_unplaced_11702',
 'LZEP_unplaced_11703',
 'LZEP_unplaced_11704',
 'LZEP_unplaced_11705',
 'LZEP_unplaced_11706',
 'LZEP_unplaced_11707',
 'LZEP_unplaced_10154',
 'LZEP_unplaced_13569',
 'LZEP_unplaced_13562',
 'LZEP_unplaced_13563',
 'LZEP_unplaced_13560',
 'LZEP_unplaced_13561',
 'LZEP_unplaced_13566',
 'LZEP_unplaced_13567',
 'LZEP_unplaced_13564',
 'LZEP_unplaced_13343',
 'LZEP_unplaced_12178',
 'LZEP_unplaced_12179',
 'LZEP_unplaced_12172',
 'LZEP_unplaced_12173',
 'LZEP_unplaced_12170',
 'LZEP_unplaced_12171',
 'LZEP_unplaced_12176',
 'LZEP_unplaced_12177',
 'LZEP_unplaced_12174',
 'LZEP_unplaced_12175',
 'LZEP_unplaced_10155',
 'LZEP_unplaced_10152',
 'LZEP_unplaced_3755',
 'LZEP_unplaced_3754',
 'LZEP_unplaced_3757',
 'LZEP_unplaced_3756',
 'LZEP_unplaced_3751',
 'LZEP_unplaced_3750',
 'LZEP_unplaced_3753',
 'LZEP_unplaced_3752',
 'LZEP_unplaced_13614',
 'LZEP_unplaced_3759',
 'LZEP_unplaced_3758',
 'LZEP_unplaced_1937',
 'LZEP_unplaced_1936',
 'LZEP_unplaced_1935',
 'LZEP_unplaced_1934',
 'LZEP_unplaced_1933',
 'LZEP_unplaced_1932',
 'LZEP_unplaced_1931',
 'LZEP_unplaced_1930',
 'LZEP_unplaced_10153',
 'LZEP_unplaced_1939',
 'LZEP_unplaced_1938',
 'LZEP_unplaced_13615',
 'LZEP_unplaced_12352',
 'LZEP_unplaced_12791',
 'LZEP_unplaced_12353',
 'LZEP_unplaced_3289',
 'LZEP_unplaced_3288',
 'LZEP_unplaced_3287',

In [5]:
Lzep_gtf = pr.read_gtf("./Jones_NEE_2023_Lzep/ref/Lasioglossum_zephyrus.filtered.gtf")
Lzep_df = Lzep_gtf.as_df()
Lzep_df

,Chromosome,Source,Feature,Start,End,Score,Strand,Frame,transcript_id,gene_id,gene_name,gene_biotype
0,LZEP_chr_1,maker,transcript,52340,53141,.,+,.,LZEP_07469-RA,LZEP_07469,LZEP_07469,protein_coding
1,LZEP_chr_1,maker,exon,52340,52489,.,+,.,LZEP_07469-RA,LZEP_07469,LZEP_07469,protein_coding
2,LZEP_chr_1,maker,exon,52558,52731,.,+,.,LZEP_07469-RA,LZEP_07469,LZEP_07469,protein_coding
3,LZEP_chr_1,maker,exon,52812,53141,.,+,.,LZEP_07469-RA,LZEP_07469,LZEP_07469,protein_coding
4,LZEP_chr_1,maker,CDS,52418,52489,.,+,0,LZEP_07469-RA,LZEP_07469,LZEP_07469,protein_coding
...,...,...,...,...,...,...,...,...,...,...,...,...
201094,LZEPmito,mitos,transcript,9875,10130,.,-,.,nad4l_t1,nad4l,MT-nad4l,protein_coding
201095,LZEPmito,mitos,exon,9875,10130,.,-,.,nad4l_t1,nad4l,MT-nad4l,protein_coding
201096,LZEPmito,mitos,gene,6912,8495,.,-,.,nad5_t1,nad5,MT-nad5,protein_coding
201097,LZEPmito,mitos,transcript,6912,8495,.,-,.,nad5_t1,nad5,MT-nad5,protein_coding
201098,LZEPmito,mitos,exon,6912,8495,.,-,.,nad5_t1,nad5,MT-nad5,protein_coding

In [6]:
chroms = Lzep_df["Chromosome"].to_list()
chroms

['LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 'LZEP_chr_1',
 ...]

In [16]:
fa_set = set(names)
gtf_set = set(chroms)
fa_set == gtf_set

False

In [17]:
print(len(fa_set))
print(len(gtf_set))

14357
1297

In [21]:
gtf_set.issubset(fa_set)

True

In [19]:
len(fa_set - gtf_set)

13060

In [20]:
len(gtf_set - fa_set)

0

In [22]:
Lzep_gff = pr.read_gff3("./LZEP_OGS_v2.1.1.gff3")
Lzep_gff_df = Lzep_gff.as_df()
Lzep_gff_df

,Chromosome,Source,Feature,Start,End,Score,Strand,Frame,ID,Name,Parent
0,LZEP_chr_1,maker,gene,52340,53141,.,+,.,LZEP_07469,LZEP_07469,NaN
1,LZEP_chr_1,maker,mRNA,52340,53141,.,+,.,LZEP_07469-RA,LZEP_07469-RA,LZEP_07469
2,LZEP_chr_1,maker,exon,52340,52489,.,+,.,LZEP_07469-RA:1,NaN,LZEP_07469-RA
3,LZEP_chr_1,maker,exon,52558,52731,.,+,.,LZEP_07469-RA:2,NaN,LZEP_07469-RA
4,LZEP_chr_1,maker,exon,52812,53141,.,+,.,LZEP_07469-RA:3,NaN,LZEP_07469-RA
...,...,...,...,...,...,...,...,...,...,...,...
211032,LZEP_unplaced_14383,maker,CDS,4332,4341,.,-,2,LZEP_11106-RB:cds,NaN,LZEP_11106-RB
211033,LZEP_unplaced_14383,maker,CDS,2062,2130,.,-,2,LZEP_11106-RB:cds,NaN,LZEP_11106-RB
211034,LZEP_unplaced_14383,maker,CDS,1007,1161,.,-,0,LZEP_11106-RB:cds,NaN,LZEP_11106-RB
211035,LZEP_unplaced_14383,maker,CDS,876,942,.,-,2,LZEP_11106-RB:cds,NaN,LZEP_11106-RB
211036,LZEP_unplaced_14383,maker,CDS,704,712,.,-,2,LZEP_11106-RB:cds,NaN,LZEP_11106-RB

In [23]:
gff_set = set(Lzep_gff_df["Chromosome"].to_list())
print(len(gff_set))

1296

In [ ]:
from pyfaidx import Fasta
import pandas as pd

fa = Fasta("./Jones_NEE_2023_Lzep/ref/Lasioglossum_zephyrus.fasta")
gtf_chroms = set()
with open("./Jones_NEE_2023_Lzep/ref/Lasioglossum_zephyrus.filtered.gtf") as f:
    for line in f:
        if not line.startswith("#"):
            gtf_chroms.add(line.split("\t")[0])

annotated_len = sum(len(fa[s]) for s in fa.keys() if s in gtf_chroms)
unannotated_len = sum(len(fa[s]) for s in fa.keys() if s not in gtf_chroms)
total_len = annotated_len + unannotated_len

print(f"已注释总长:{annotated_len/1e6:.1f} Mb ({annotated_len/total_len*100:.1f}%)")
print(f"未注释总长:{unannotated_len/1e6:.1f} Mb ({unannotated_len/total_len*100:.1f}%)")

已注释总长:242.0 Mb (87.8%)
未注释总长:33.7 Mb (12.2%)